### ISSUE TITLE
Better exceptions

### ISSUE THREAD

**Issue by wvteijlingen** [jorttbv/bunq-client#13]
Some exceptions are instantiated with a hash, for example in the `Resource` class:

```ruby
fail UnexpectedResponse.new(code: response.code, headers: response.raw_headers, body: response.body)
```

These hashes are converted to strings and end up in a serialised form in the exception `message`. This makes it very hard to extract the actual cause from an exception. I think it would be better if these exceptions are custom subclasses with additional accessors

```ruby
class UnexpectedResponse < StandardError
  attr_reader :status_code
  attr_reader :headers
  attr_reader :body

  def initialize(msg = "Unexpected response", status_code: nil, headers: nil, body: nil)
    @status_code = status_code
    @headers = headers
    @body = body
    super(msg)
  end
end

exception = UnexpectedResponse.new("Descriptive message", status_code: 404, headers: {foo: 'bar'}, body: 'Body')
exception.message # Descriptive message
exception.code # 404
exception.headers # {foo: 'bar'}
exception.body # Body
```

Since the Bunq API has a standard JSON layout for 4xx errors, the exception message could be derived from the JSON.

**Comment by lvonk** [comment]
Yes I agree. That is much better. Feel free to create a PR, otherwise I will pick this up at the end of the week.

**Comment by wvteijlingen** [comment]
Cool. I'll try to whip up a PR.

**Comment by wvteijlingen** [comment]
https://github.com/jorttbv/bunq-client/pull/14
