### ISSUE TITLE
No instruction how to upgrade the gem

### ISSUE THREAD

**Issue by romikoops** [jorttbv/bunq-client#35]
Hello. It is nice to see the gem moves forward and is alive. It was went up to version [0.7.2](../tree/v0.7.2) from [0.2.0](../tree/v0.2.0) during short period of time. At the same time there is no information what was changed exactly and which brake changes were introduced. 

It would be really nice to support [CHANGELOG](../blob/master/CHANGELOG.md) file with last changes. Now it looks abandoned.

In additional, it would be really appreciated to add Upgrade instructions in [README](../blob/master/README.md) file.

Anyway, thank you for such amazing gem. I am ready to contribute to it.

**Comment by bforma** [comment]
Yes, you are right that we should update the CHANGELOG. Going to try to reminder doing that in the future.

**Comment by bforma** [comment]
I think most (if not all) recent changes were backwards compatible.
